apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001