apiVersion: v1
kind: Service
metadata:
  name: filebeat
spec:
  selector:
    app: filebeat
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
      nodePort: 30082